### ISSUE TITLE
Seems like `layout` is required in version 0.6, but not documented or typed

### ISSUE THREAD

**Issue by bramkragten** [PolymerLabs/uni-virtualizer#103]
The layout option seems to be required, but it is typed as optional and not documented.

Should this by default fallback to `Layout1d`, or should it be made a required option?

https://github.com/PolymerLabs/uni-virtualizer/blob/master/packages/lit-virtualizer/src/lib/scroll.ts#L20-L21

**Comment by afberg** [comment]
I'm running into the same issue (I think) when upgrading to Lit 2.0 and using the latest version of the `lit-virtualizer` element (v.0.6.0).

Below is the error I'm getting which indeed seems to be related to the `layout` property:
```
Uncaught (in promise) TypeError: Cannot set property 'totalItems' of undefined
    at VirtualScroller._updateLayout 
    at VirtualScroller._schedule
```

**Comment by lucienimmink** [comment]
Same issue, a very bare example already fails
```javascript
  <lit-virtualizer
    .items=${[1,2,3,4,5,6,7]}
    .renderItem=${(item: any) => html`${item}`}
  >
  </lit-virtualizer>
```
results in error
```
Uncaught (in promise) TypeError: Cannot set property 'totalItems' of undefined
    at VirtualScroller._updateLayout 
    at VirtualScroller._schedule
```

**Comment by lucienimmink** [comment]
A quick fix is doing to following (though this needs refactoring!)
```javascript
import {Layout1d} from '@lit-labs/virtualizer';

<lit-virtualizer
    .items=${[1,2,3,4,5,6,7]}
    .renderItem=${(item: any) => html`${item}`}
    .layout=${Layout1d}
>
</lit-virtualizer>

**Comment by graynorton** [comment]
Just to confirm: this was a change introduced in 0.6, but it will be reverted in the next release. The workaround in the meantime is to explicitly load a layout, as commenters have noted.
