### ISSUE TITLE
Cannot scroll up

### ISSUE THREAD

**Issue by tpluscode** [PolymerLabs/uni-virtualizer#108]
I found this annoying behaviour when trying to scroll up a `lit-virutalizer`. It appears to loop the `rangechange` event on two topmost items, preventing scroll

This is a long list of dynamic lit@2 elements. New data is being loaded dynamically and `array.spliced` into the array

Not sure if I will be able to minimally reproduce this yet. Check out the recording below. Going down, the `rangechange` is fired with increasing indexes. Going up, you see it gets stuck between N and N-1. 

https://user-images.githubusercontent.com/588128/129676567-3d083392-7286-4d16-976d-9f03cd5c1e4b.mp4

**Comment by graynorton** [comment]
Thanks for the report. I think I will need to be able to repro this (ideally with a minimal case, otherwise by being able to interact with and debug the full app) in order to diagnose and fix.

**Comment by tpluscode** [comment]
Thank you @graynorton. I won't have the bandwidth immediately available to try a minimal repro.

Here is the repo: https://github.com/zazuko/zack-search if you would have the chance to check the full app. The virtualiser is in `zack-results` component and data being loaded by `ResultsController`

**Comment by tpluscode** [comment]
Any luck @graynorton?

**Comment by graynorton** [comment]
@tpluscode I tried taking a look today and was able to repro your issue locally using your project. I confirmed that it no longer reproduces when I use the latest (as yet unreleased) version of `@lit-labs/virtualizer` I have locally. This new version contains a bunch of fixes; I have a guess which one is relevant to your issue, but haven't yet confirmed. I'd like to get a new release out soon in any case, as I've also fixed most to all of the other reported issues, but timing is a bit up in the air. Do you have any particular deadlines you're working toward?

**Comment by tpluscode** [comment]
Great news, thank you! 

I do not have a particular deadline TBH but I would appreciate a new version some time this month. WDYT?

**Comment by cintaccs** [comment]
just to show interest - I would like to add that upgrading to the new lit lib from older lit-element used on approx 50 components - the main obstacle is that we can’t figure out how to migrate the older lit-virtualizer … I would hope soon to be able to use an upgraded virtualizer … initially it did not work with the current available on lit-labs
