### ISSUE TITLE
lit-virtializer renderItem index refers to the item position in the rendered list, not the original list of items

### ISSUE THREAD

**Issue by afberg** [PolymerLabs/uni-virtualizer#109]
The `index` used in the `renderItem` property for the `lit-virtualizer` component no longer refers to an items index in the overall list but rather its index in the list of rendered items.

Reproducible by the following code:

```html
<lit-virtualizer
  .items=${items}
  .renderItem=${(_item, index) => html`${index}`}
  >
</lit-virtualizer>
```

**Comment by graynorton** [comment]
Yes, this is a known issue (though there's no GH issue for it) that has been fixed and will be resolved in the next release (which I'm trying to get out ASAP). Thanks for reporting!

Will leave this open until the release goes out.
