### ISSUE TITLE
Consider renaming `template` to `renderItem`

### ISSUE THREAD

**Issue by justinfagnani** [PolymerLabs/uni-virtualizer#14]
"template" is a overloaded and slightly vague term in lit-html parlance. It can refer to the tagged template expression, or to a function that returns a TemplateResult.

I think naming this like a render method makes it most clear, and works better with subclassing, where the subclass would implement a `renderItem()` method. A `template()` method would be ambiguous in this context.

**Comment by straversi** [comment]
I agree, I found myself getting confused with this.
