### ISSUE TITLE
Maximum size of virtualizer is artificially limited

### ISSUE THREAD

**Issue by graynorton** [PolymerLabs/uni-virtualizer#140]
**Description:**

At some point in the past, we ran into strange (and bad) behaviors in one or more browsers when sizing a virtualizer beyond a certain number of pixels.

As a clumsy workaround, we are currently clamping the maximum height to an arbitrary value that was determined through ad hoc experimentation.

We need to investigate more deeply to see if we can solve this problem in a fundamental way, or (failing that) at least come up with a better workaround.

**Repro:**

1. Load this playground example: https://lit.dev/playground/#gist=346adebe77f9950d2fbc90e6758f4d79
2. Scroll all the way to the bottom of the list in the playground's **Result** pane (you'll probably want to do this by dragging the thumb)

**Expected Result:**

You can scroll all the way to the 1,000,000th item

**Actual Result:**

You can't

**Comment by usergenic** [comment]
Now tracking this issue at https://github.com/lit/lit/issues/3572 so closing this here.
