### ISSUE TITLE
Publish the TS definition files

### ISSUE THREAD

**Issue by web-padawan** [PolymerLabs/uni-virtualizer#29]
Hi! I'm trying to use `lit-virtualizer` in a TS project, namely my prototype of a combo-box component, as a potential successor to `vaadin-combo-box` (which uses `iron-list`).

https://github.com/web-padawan/lit-combo-box

The 0.3.0 version of `lit-virtualizer` is lacking any typings, so I had to use `any` in my own TS code and I'm getting a bunch of warnings from `lit-analyzer`.

@straversi @justinfagnani do you mind publishing a new release with typings?
That would also help to deliver #28 which was merged last week.

I can submit a PR to tweak `tsconfig.json` accordingly.

**Comment by justinfagnani** [comment]
@web-padawan a PR would be great!

**Comment by web-padawan** [comment]
Fixed by #31.
