### ISSUE TITLE
Choose a ResizeObserver polyfill

### ISSUE THREAD

**Issue by graynorton** [PolymerLabs/uni-virtualizer#63]
## Description

We need a ResizeObserver polyfill for old Edge and IE11 support and need to decide between que-etc/resize-observer-polyfill (for which we have a working version of ShadowDOM support) and juggle/resize-observer (which doesn't yet support ShadowDOM but is much more actively maintained).

## Acceptance Criteria

Have a decision, backed up by:

* Performance data (ideally measured specifically in old Edge and IE11, since that's where it matters)
* Path to near-term and long-term ShadowDOM support
* Fit for importing into Google monorepo
* Level of maintainer support

**Comment by cintaccs** [comment]
Hi, I am using your virtualizer - and appreciate a lot what you have done/are doing! I am wondering why you would bother creating support for IE11 and old Edge for any new versions. What would be against not supporting IE11 and old Edge - Microsoft hardly want to support these browsers themself... and the UI experience in general in those browsers are in general lacking more and more behind, they are not up to date from a security point of view etc. etc. We need as a community to move forward - legacy browser support can't go on forever.... just my 2 cents... :-)

**Comment by graynorton** [comment]
We'll go with `que-etc/resize-observer`.

It's less popular and not actively maintained, but performs substantially better with `lit-virtualizer`, and that is more important for our current purposes.

Changing polyfills in the future, should the need arise, should be straightforward.

```
├─────────────────────────────────┼─────────┼───────────────────────┼───────────────────────┼────────────────────────┼
│ @juggle/resize-observer (IE)    │ ie      │ 4539.47ms - 4803.39ms │                       │                 slower │
│                                 │         │                       │              -        │              31% - 44% │
│                                 │         │                       │                       │  1078.67ms - 1464.17ms │
├─────────────────────────────────┼─────────┼───────────────────────┼───────────────────────┼────────────────────────┼
│ resize-observer-polyfill (IE)   │ ie      │ 3259.52ms - 3540.50ms │                faster │                        │
│                                 │         │                       │             24% - 31% │               -        │
│                                 │         │                       │ 1078.67ms - 1464.17ms │                        │
├─────────────────────────────────┼─────────┼───────────────────────┼───────────────────────┼────────────────────────┼

├─────────────────────────────────┼─────────┼───────────────────────┼─────────────────────┼──────────────────────┤
│ @juggle/resize-observer (Edge)  │ edge    │ 2689.70ms - 3095.71ms │                     │               slower │
│                                 │         │                       │            -        │            13% - 33% │
│                                 │         │                       │                     │  306.50ms - 759.26ms │
├─────────────────────────────────┼─────────┼───────────────────────┼─────────────────────┼──────────────────────┤
│ resize-observer-polyfill (Edge) │ edge    │ 2259.63ms - 2460.02ms │              faster │                      │
│                                 │         │                       │           12% - 25% │             -        │
│                                 │         │                       │  306.5ms - 759.26ms │                      │
└─────────────────────────────────┴─────────┴───────────────────────┴─────────────────────┴──────────────────────┘
```
