### ISSUE TITLE
Breaks with new Lit 2.0

### ISSUE THREAD

**Issue by kjantzer** [PolymerLabs/uni-virtualizer#94]
Recently upgraded to [lit 2.0](https://www.npmjs.com/package/lit) and it looks like using `html()` with `renderItem` no longer works.

`[object Object]` is printed instead of HTML

**Comment by lucienimmink** [comment]
Same issue, hopefully this can be resolved

**Comment by herberthobregon** [comment]
This WC needs to be updated to 2.0 🔥 @graynorton

**Comment by graynorton** [comment]
The latest release (0.6.0) works with Lit 2.0.

https://www.npmjs.com/package/@lit-labs/virtualizer

**Comment by herberthobregon** [comment]
New release doesn’t work https://github.com/lit/lit/issues/1965 any fix for this? Or the implementation is wrong?
